<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="main.css"/>
    <title>Portfolio</title>
</head>
<body>
    <header class="wrapper">
        <div class="one">
            <img src="images/LogoDanV4.png" alt="logo de daniel" id="logo">
        </div>
        <div id='burger'>
            <div class='burger'></div>
            <div class='burger'></div>
            <div class='burger'></div>
        </div>
        <div class = "two hide">
            <nav class="hide">
                <ul id="menu">
                    <li><a href="#techno">Technologies</a></li>
                    <li><a href="#projets">Projets</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <section id="section_titre">
        <div class="contain">
            <svg width="1100px" height="300px" fill="url(#Gradient1)" id="svg1">
                <defs>
                    <radialGradient id="Gradient1" cy="60%" fx="45%" fy="45%" r="2">
                        <stop offset="0%" stop-color="#48afc1" />
                        <stop offset="10%" stop-color="#b4c63b" />
                        <stop offset="20%" stop-color="#ef5b2b" />
                        <stop offset="30%" stop-color="#503969" />
                        <stop offset="40%" stop-color="#ab6294" />
                        <stop offset="50%" stop-color="#1cb98f" />
                        <stop offset="60%" stop-color="#48afc1" />
                        <stop offset="70%" stop-color="#b4c63b" />
                        <stop offset="80%" stop-color="#ef5b2b" />
                        <stop offset="90%" stop-color="#503969" />
                        <stop offset="100%" stop-color="#ab6294" />
                    </radialGradient>
                </defs>
                <text x="15%" y="75%" id="text_title">Developer full-stack junior</text>
            </svg>
        </div>
        <svg class='opacity' width="2200" height="400" version="1.1" xmlns="http://www.w3.org/2000/svg" id="svg2">

            <circle cx="216" cy="197" r="33" fill="#FEEB31" />

            <line x1="268" x2="437" y1="131" y2="316" stroke="#166D2F"  stroke-width="40" stroke-linecap="round"/>

            <line x1="520" x2="627" y1="180" y2="80" stroke="#000000"  stroke-width="48"/>

            <circle cx="585" cy="330" r="34" fill="#15A1DB"/>

            <rect class='transformSVG' x='665' y='-320' width=115px height=115px fill="#E44C24" rx='30' ry='30'/>

            <rect class='transformSVG' x='670' y='-580' width=85px height=85px fill="#2BA03C" rx='20' ry='20'/>

            <rect class='transformSVG' x='900' y='-485' width=80px height=80px fill="#F59054" rx='20' ry='20'/>

            <line x1="1050" x2="1229" y1="191" y2="376" stroke="#3EAC8F"  stroke-width="45" stroke-linecap="round"/>

            <rect class='transformSVG' x='1040' y='-685' width=75px height=75px fill="#85E6C1"/>

            <line x1="1485" x2="1669" y1="131" y2="316" stroke="#E44C24"  stroke-width="40" stroke-linecap="round"/>

            <rect class='transformSVG' x='1030' y='-1010' width=140px height=140px fill="#006CB8"/>

            <rect class='transformSVG' x='1260' y='-800' width=20px height=20px fill="#006CB8"/>

            <rect class='transformSVG' x='1280' y='-1040' width=80px height=80px fill="#2BA03C" rx='25' ry='25'/>

            <rect class='transformSVG' x='1420' y='-1150' width=110px height=110px fill="#E8C931" rx='30' ry='30'/>

            <rect class='transformSVG' x='360' y='-200' width=20px height=20px fill="#85E6C1"/>

        </svg>
    </section>
    <section>
        <h2 id="techno">Technologies</h2>
        <p class="ss-titre"><em>Création de sites Web du front au back-end, du site from scratch au CMS</em></p>
        <div class="wrapper-1">
            <div class="one-1">
                <figure>
                    <img src="images/html_img.png" alt="logo_html" />
                    <figcaption>HTML 5</figcaption>
                </figure>
                <p class="text-logo">J'utilise les techniques les plus récentes pour un rendu html inégalable et précis.</p>
            </div>
            <div class="two-1">
                <figure>
                    <img src="images/css_img.png" alt="logo_css" />
                    <figcaption>CSS 3</figcaption>
                </figure>

                <p class="text-logo">La forme de vos pages web sera adaptée au pixel près grâce aux techniques css.</p>
            </div>
            <div class="three">
                <figure>
                    <img src="images/js_img.png" alt="logo_css" />
                    <figcaption>Javascript</figcaption>
                </figure>

                <p class="text-logo">Sans élément dynamiques dans votre site, il vous manquera le côté intéractif.</p>
            </div>
            <div class="four">
                <figure>
                    <img src="images/php_img.png" alt="logo_php" />
                    <figcaption>Php</figcaption>
                </figure>

                <p class="text-logo" id="text_php">Php est incontournable en programmation et afin d'intéragir avec les bases de données.</p>
            </div>
            <div class="five">
                <figure>
                    <img src="images/mysql_img.png" alt="logo_mysql" />
                    <figcaption>Mysql</figcaption>
                </figure>

                <p class="text-logo" >Pas de site web sans donnée, MySql est l'indispensable complément de Php.</p>
            </div>
            <div class="six">
                <figure>
                    <img src="images/jquery_v2.png" alt="logo_jquery" />
                    <figcaption>Bootstrap/Jquery</figcaption>
                </figure>

                <p class="text-logo" id="text_bootstrap">Le couple gagnant du Web, utilisé dans la majorité des sites internet, apportant rapidité et efficacité.</p>
            </div>
            <div class="seven">
                <figure>
                    <img src="images/wordpress_img.png" alt="logo_wordpress" />
                    <figcaption>Wordpress</figcaption>
                </figure>

                <p class="text-logo">Les possibilités de personnalisation sont infinis grâce à ce Content Manager System.</p>
            </div>
            <div class="eight">
                <figure>
                    <img src="images/symfony_img.png" alt="logo_symfony" />
                    <figcaption>Symfony</figcaption>
                </figure>

                <p class="text-logo" id="text_symfony">Utilisé par la grande majorité des entreprises françaises, Symfony est le must des frameworks Php.</p>
            </div>

        </div>
    </section>
    <section>
        <h2 id="projets">Projets récents</h2>
        <p class="ss-titre"><em>Retrouvez tous mes projets en détail en cliquant dessus !</em></p>
    </section>
    <section>
        <h2 id="contact">Contact</h2>
        <p class="ss-titre"><em>Partagez ma passion du Web !</em></p>

    </section>
    <script src="main.js"></script>
</body>
</html>