<?php //session_start(); ?>

<h1 style="text-align:center;padding:40px;border-top:1px lightgrey solid;">Articles récents</h1>

<!--<pre>-->
<!--    --><?php //print_r($flashbag); ?>
<!--</pre>-->


<article class="wrapper_blog">

    <div class="wrapper_blog_zero">

        <aside>
            <ul>
                Liste des articles :<br><br>
                <?php foreach ($posts as $post) { ?>
                    <li><u><?= $post['Title'] ?> </u></li>
                <?php } ?>
            </ul>
        </aside>
    </div>
    <div class="wrapper_blog_one">
        <?php foreach ($posts as $post) { ?>
            <h3 class="title_post">
                <?php echo $post['Title']; ?>
            </h3>
            <small>
                <?php	echo $post['CreatedAt']; ?>
            </small>

            <p>
                <?php	echo $post['Content']; ?>

            </p>
                <?php if(!empty($post['Image'])){ ?>

                    <img id="imageAvatar" src="assets/images/<?php  echo $post['Image']; ?>" alt=''/>


                <?php } ?>
            <p>
                <?php if ($post['Category'] === '1') { ?>
                <small>Divers</small>
                <?php } ?>
            </p>
        <?php } ?>
    </div>

</article>






