<?php session_start(); ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="assets/images/LogoDanV4.png" />
    <link rel="stylesheet" href="assets/css/main.css"/>
    <link rel="stylesheet" href="assets/css/carroussel.css" />
    <title>Portfolio</title>
</head>
<header class="wrapper">
    <div class="one">
        <a href="index.php"><img src="assets/images/LogoDanV4.png" alt="logo de daniel" id="logo"></a>
    </div>
    <div id='burger'>
        <div class='burger'></div>
        <div class='burger'></div>
        <div class='burger'></div>
    </div>
    <div class = "two hide">
        <nav class="hide">
            <ul id="menu">
                <?php  if ($page==='index') { ?>
                    <li><a href="index.php#projets">Projets</a></li>
                    <li><a href="index.php#techno">Technologies</a></li>
                    <li><a href="index.php#contact">Contact</a></li>
<!--                <li><a href="index.php?p=blog">Blog</a></li>-->
                <?php } else { ?>
                    <li><a href="index.php">Accueil</a></li>
                    <li><a href="index.php?p=blog">Blog</a></li>
                    <li><a href="index.php?p=user">Utilisateur</a></li>
                <?php } ?>
            </ul>
        </nav>
    </div>
</header>
<p style="text-align: center;padding: 20px;">
    <?php $userSession = new UserSession(); ?>
    <?php if ($userSession->isAuthenticated()): ?>

        Bonjour <em><u id="texteUserSession"><?=$userSession->getUserName()?></u></em>
    <?php endif ?>
</p>