
<div style="display:grid; grid-template-columns: 3(1,fr);">
    <div style="grid-column: 2;">
        <h1>La page de l'utilisateur</h1>
        <nav>
            <ul>
                <?php $userSession = new UserSession(); ?>
                <?php if ($userSession->isAuthenticated()): ?>

                    <li>Bonjour <em><?=$userSession->getUserName()?></em> </li>
                    <li><a href="index.php?p=signout">Déconnexion</a></li>
                <?php else: ?>
                    <li><a href="index.php?p=signup">Créer un compte</a></li>
                    <li><a href="index.php?p=signin">Connexion</a></li>
                <?php endif; ?>


            </ul>
        </nav>
    </div>

</div>



					
					
					
					
	
	
		


	




	

	
	
	
