
<body>

<!--    <pre>-->
<!--    --><?php //print_r($page); ?>
<!--    </pre>-->
    <section id="section_titre">
        <div class="contain">
            <svg width="1100px" height="300px" fill="url(#Gradient1)" id="svg1">
                <defs>
                    <radialGradient id="Gradient1" cy="60%" fx="45%" fy="45%" r="2">
                        <stop offset="0%" stop-color="#48afc1" />
                        <stop offset="10%" stop-color="#b4c63b" />
                        <stop offset="20%" stop-color="#ef5b2b" />
                        <stop offset="30%" stop-color="#503969" />
                        <stop offset="40%" stop-color="#ab6294" />
                        <stop offset="50%" stop-color="#1cb98f" />
                        <stop offset="60%" stop-color="#48afc1" />
                        <stop offset="70%" stop-color="#b4c63b" />
                        <stop offset="80%" stop-color="#ef5b2b" />
                        <stop offset="90%" stop-color="#503969" />
                        <stop offset="100%" stop-color="#ab6294" />
                    </radialGradient>
                </defs>
                <text x="15%" y="75%" id="text_title">Developer full-stack junior</text>
            </svg>
        </div>
        <svg class='opacity' width="2200" height="400" version="1.1" xmlns="http://www.w3.org/2000/svg" id="svg2">

            <circle cx="216" cy="197" r="33" fill="#FEEB31" />

            <line x1="268" x2="437" y1="131" y2="316" stroke="#166D2F"  stroke-width="40" stroke-linecap="round"/>

            <line x1="520" x2="627" y1="180" y2="80" stroke="#000000"  stroke-width="48"/>

            <circle cx="585" cy="330" r="34" fill="#15A1DB"/>

            <rect class='transformSVG' x='665' y='-320' width=115px height=115px fill="#E44C24" rx='30' ry='30'/>

            <rect class='transformSVG' x='670' y='-580' width=85px height=85px fill="#2BA03C" rx='20' ry='20'/>

            <rect class='transformSVG' x='900' y='-485' width=80px height=80px fill="#F59054" rx='20' ry='20'/>

            <line x1="1050" x2="1229" y1="191" y2="376" stroke="#3EAC8F"  stroke-width="45" stroke-linecap="round"/>

            <rect class='transformSVG' x='1040' y='-685' width=75px height=75px fill="#85E6C1"/>

            <line x1="1485" x2="1669" y1="131" y2="316" stroke="#E44C24"  stroke-width="40" stroke-linecap="round"/>

            <rect class='transformSVG' x='1030' y='-1010' width=140px height=140px fill="#006CB8"/>

            <rect class='transformSVG' x='1260' y='-800' width=20px height=20px fill="#006CB8"/>

            <rect class='transformSVG' x='1280' y='-1040' width=80px height=80px fill="#2BA03C" rx='25' ry='25'/>

            <rect class='transformSVG' x='1420' y='-1150' width=110px height=110px fill="#E8C931" rx='30' ry='30'/>

            <rect class='transformSVG' x='360' y='-200' width=20px height=20px fill="#85E6C1"/>

        </svg>
    </section>
    <section>
        <h2 id="projets">Projets récents</h2>
        <p class="ss-titre"><em>Retrouvez tous mes projets en détail en cliquant dessus !</em></p>

        <div class="wrapper-2">
            <div class="one-2 align_grid box text_projet" style="position: relative;">
                <a href="#openModal">
                    <div class="clic"><p class="text_clic" style="font-size: 1.5rem;">click-me</p></div>
                    <img src="assets/images/alumni-1.png" alt="logo_symfony" />
                    <h3>Symfony</h3>
                    <p>Alumni : annuaire des anciens élèves du GRETA<br>
                    Projet réalisé en formation Développeur Web et Web Mobile.</p>
                </a>
                <div id="openModal" class="modalDialog">
                    <div>
                        <a href="#close" title="Close" class="close">Fermer</a>
                        <h2 class='hanamiH2'>Symfony : Alumni</h2>
                        <div class="slider">
                            <div class="container">
                                <div id="slider">
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/al_3_420.PNG 420w,
                                                 assets/images/al_3.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/al_1_420.PNG 420w,
                                                 assets/images/al_1.png"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/al_2_420.PNG 420w,
                                                 assets/images/al_2.png"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/al_4_420.PNG 420w,
                                                 assets/images/al_4.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/al_5_420.PNG 420w,
                                                 assets/images/al_5.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="two-2 align_grid box text_projet" style="position: relative;">
                <a href="#openModal1">
                    <div class="clic"><p class="text_clic" style="font-size: 1.5rem;">click-me</p></div>
                    <img src="assets/images/hy_1.PNG" alt="Accueil du site hydratis" />
                    <h3>From Scratch</h3>
                    <p>Hydratis : projet réalisé pour la société d'ingénierie hydraulique Hydratis.<br>
                       Site réalisé pour le compte de l'agence Web E-partenaire.</p>

                </a>
                <div id="openModal1" class="modalDialog">
                    <div>
                        <a href="#close" title="Close" class="close">Fermer</a>
                        <h2 class='hanamiH2'>From scratch : Hydratis</h2>
                        <div class="slider">
                            <div class="container">
                                <div id="slider1">
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/hy_1_420.PNG 420w,
                                                 assets/images/hy_1.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/hy_2_420.PNG 420w,
                                                 assets/images/hy_2.PNG "
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/hy_4_420.PNG 420w,
                                                assets/images/hy_3.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/hy_4.5_420.PNG 420w,
                                                 assets/images/hy_4.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/hy_5_420.PNG 420w,
                                                 assets/images/hy_5.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="three-2 align_grid box text_projet" style="position: relative;">
                <a href="#openModal2">
                    <div class="clic"><p class="text_clic" style="font-size: 1.5rem;">click-me</p></div>
                    <img src="assets/images/se_1.PNG" alt="Accueil du site SECTP" />
                    <h3>Wordpress</h3>
                    <p>SECTP: projet réalisé pour la société de travaux provençale SECTP.<br>
                        Site réalisé pour le compte de l'agence Web E-partenaire.</p>
                </a>
                <div id="openModal2" class="modalDialog">
                    <div>
                        <a href="#close" title="Close" class="close">Fermer</a>
                        <h2 class='hanamiH2'>Wordpress : SECTP</h2>
                        <div class="slider">
                            <div class="container">
                                <div id="slider2">
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/se_1_420.PNG 420w,
                                                         assets/images/se_6.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/se_2_420.PNG 420w,
                                                          assets/images/se_7.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/se_3_420.PNG 420w,
                                                        assets/images/se_8.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="item__image">
                                            <img srcset="assets/images/se_7_420.PNG 420w,
                                                         assets/images/se_9.PNG"
                                                 alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p style="text-align: center; margin-top:2%;">Si vous voulez voir plus de code, <u><a href="assets/images/daniel_provost.pdf" target="_blank">c'est ici !</a></u></p>
    </section>
<section>
    <h2 id="techno">Technologies</h2>
    <p class="ss-titre"><em>Création de sites Web du front au back-end, du site from scratch au CMS</em></p>
    <div class="wrapper-1">
        <div class="one-1 align_grid_tech box">
            <figure>
                <img src="assets/images/html_img.png" alt="logo_html" />
                <figcaption>HTML 5</figcaption>
            </figure>
            <p class="text-logo">J'utilise les techniques les plus récentes pour un rendu html inégalable et précis.</p>
        </div>
        <div class="two-1 align_grid_tech box">
            <figure>
                <img src="assets/images/css_img.png" alt="logo_css" />
                <figcaption>CSS 3</figcaption>
            </figure>

            <p class="text-logo">La forme de vos pages web sera adaptée au pixel près grâce aux techniques css.</p>
        </div>
        <div class="three align_grid_tech box">
            <figure>
                <img src="assets/images/js_img.png" alt="logo_css" />
                <figcaption>Javascript</figcaption>
            </figure>

            <p class="text-logo">Sans élément dynamiques dans votre site, il vous manquera le côté intéractif.</p>
        </div>
        <div class="four align_grid_tech box">
            <figure>
                <img src="assets/images/php_img.png" alt="logo_php" />
                <figcaption>Php</figcaption>
            </figure>

            <p class="text-logo" id="text_php">Php est incontournable en programmation et afin d'intéragir avec les bases de données.</p>
        </div>
        <div class="five align_grid_tech box">
            <figure>
                <img src="assets/images/mysql_img.png" alt="logo_mysql" />
                <figcaption>Mysql</figcaption>
            </figure>

            <p class="text-logo" >Pas de site web sans donnée, MySql est l'indispensable complément de Php.</p>
        </div>
        <div class="six align_grid_tech box">
            <figure>
                <img src="assets/images/jquery_v2.png" alt="logo_jquery" />
                <figcaption>Bootstrap/Jquery</figcaption>
            </figure>

            <p class="text-logo" id="text_bootstrap">Le couple gagnant du Web, utilisé dans la majorité des sites internet, apportant rapidité et efficacité.</p>
        </div>
        <div class="seven align_grid_tech box">
            <figure>
                <img src="assets/images/wordpress_img.png" alt="logo_wordpress" />
                <figcaption>Wordpress</figcaption>
            </figure>

            <p class="text-logo">Les possibilités de personnalisation sont infinis grâce à ce Content Manager System.</p>
        </div>
        <div class="eight align_grid_tech box">
            <figure>
                <img src="assets/images/symfony_img.png" alt="logo_symfony" />
                <figcaption>Symfony</figcaption>
            </figure>

            <p class="text-logo" id="text_symfony">Utilisé par la grande majorité des entreprises françaises, Symfony est le must des frameworks Php.</p>
        </div>
    </div>
</section>
    <section>
        <h2 id="contact">Parcours et contact</h2>
        <p class="ss-titre"><em>Partagez ma passion du Web !</em></p>
        <p id="coordonnées">Vous pouvez me contacter soit par <u><a href="mailto:dprovost67@gmail.com">mail</a> </u> :<br>
            dprovost67@gmail.com<br>
            ou par <u><a href="tel:0689118020">téléphone</a> </u> :<br> 06 89 11 80 20.</p>
        <div class= "wrapper-3">
            <figure class="one-3">
                <img class="img_cv" src="assets/images/cv.jpg" alt="portrait_daniel">
            </figure>
            <div class="two-3">
                <p>Je suis un développeur passionné, étudiant au Greta à Aix-en-Provence. En reconversion professionnelle je réalise des sites depuis 2018.</p>
                <div class="triangle"><div class="triangle1"></div></div>
                <p><a class="color_link" href="mailto:dprovost67@gmail.com">dprovost67@gmail.com</a></p>
                <p>(Web developer)</p>
            </div>
        </div>
    </section>
    <footer>
        <a href="#logo" ><div class="bouton_scroll"><span>&#x21E1</span></div></a>
    </footer>
    <script src="assets/js/main.js"></script>
    <script src="assets/js/carroussel.js"></script>
</body>
</html>