<?php include 'header.phtml'; ?>



    	<section>
        	<h2>Connexion</h2>
			<?php if(isset($error)):?>
			<p class='error'>
			<?= $error;?>
			</p>
			<?php endif; ?>
			
            <form action="index.php?p=signin" method="POST">
            	<fieldset>
                	<ul>
                    	<li>
                        	<label for="email">Email</label>
                            <input type="email" id="email" name="email" <?php if(isset($email)){ echo 'value="'.$email.'"';}?>>
                        </li>
                        <li>
                        	<label for="password">Mot de passe</label>
                            <input type="password" id="password" name="password" <?php if(isset($password)){ echo 'value="'.$password.'"';}?>>
                        </li>
                    </ul>
                </fieldset>
                <input type="submit" value="Connexion">
            </form>
         </section>    	


